language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CXX=g++-8"

    - os: osx
      osx_image: xcode10.1

    - os: osx
      osx_image: xcode10.2
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DDBG_MACRO_BUILD_TESTS=ON -DDBG_MACRO_BUILD_EXAMPLES=ON
  - make -j2
  - ctest
  - ./examples/example_factorial
  - ./examples/example_gcd
  - ./examples/example_temperature
