language: cpp


matrix:
  include:
    - os: linux
      image: xenial
      compiler: clang
      env:
        - CPP_STANDARD=11

    - os: linux
      image: xenial
      compiler: clang
      env:
        - CPP_STANDARD=14

    - os: linux
      image: xenial
      compiler: clang
      env:
        - CPP_STANDARD=17

    - os: linux
      image: xenial
      compiler: gcc
      env:
        - CPP_STANDARD=11

    - os: linux
      image: xenial
      compiler: gcc
      env:
        - CPP_STANDARD=14

    - os: linux
      image: xenial
      compiler: gcc
      env:
        - CPP_STANDARD=17

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install g++-8 libstdc++-8-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_STANDARD=${CPP_STANDARD} ..
  - make
  - ./dbg_macro-example
  - ./dbg_macro-demo
  - ./dbg_macro-tests
  - ./dbg_macro-tests-macro_disabled
